### ISSUE TITLE
dotnet-lambda tool is not auto installed

### ISSUE THREAD

**Issue by johniwasz** [aws/aws-vsts-tools#259]
**Describe the bug**
I'm using Azure DevOps and in the Lambda build task that was working prior to version 1.2.0. 

 I'm getting the following error in a package lambda task with version 1.3.0.

```
The task also requires permissions to upload your Lambda function or serverless application content to the specified Amazon S3 bucket. Depending on the size of the application bundle, either putObject or the S3 multi-part upload APIs may be used.
==============================================================================
Processing Lambda project at /home/vsts/work/1/s/src/[PROJECTNAMEREDACTED]
Reading existing aws-lambda-tools-defaults.json
Clearing out profile [PROFILENAMEREDACTED] so task credentials will be used.
Configuring credentials for task
No credentials configured.The task will attempt to use credentials found in the build host environment.
Configuring region for task
...configured to use region us-east-1, defined in task.
Beginning dotnet restore
Path to tool: /usr/bin/dotnet
[command]/usr/bin/dotnet restore
  Restore completed in 48.57 ms for /home/vsts/work/1/s/src/[PROJNAMEREDACTED].csproj.
Beginning Lambda Deployment
Performing package-only build of function, output package will be placed in /home/vsts/work/1/a/packageddeployment.zip
Path to tool: /usr/bin/dotnet
[command]/usr/bin/dotnet lambda package -o /home/vsts/work/1/a/packageddeployment.zip --region us-east-1 -fn [FUNCTIONAMEREDACTED] -fh [HANDLERREDACTED] --function-role [ROLEREDACTED] --function-memory-size 1024 --function-timeout 60 --disable-interactive true --no-build
No executable found matching command "dotnet-lambda"
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
##[section]Finishing: Package  [LAMBDANAMEREDACTED]
```

I installed lambda tools in a prior task:

```
##[section]Starting: Install Global Amazon.Lambda.Tools
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.153.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
[command]/usr/bin/dotnet tool install Amazon.Lambda.Tools -g
Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: dotnet-lambda
Tool 'amazon.lambda.tools' (version '3.2.3') was successfully installed.
##[section]Finishing: Install Global Amazon.Lambda.Tools
```

----------------

The build task and unit testing tasks complete, but the Lambda packaging task fails with the dotnet-lambda tool not found.

**To reproduce**
See above. Can provide detailed logs to a private email.

**Expected behavior**
Expected the following command line executed in the lamdba package step to produce a zip file:

/usr/bin/dotnet lambda package -o /home/vsts/work/1/a/packageddeployment.zip --region us-east-1 -fn [FUNCTIONAMEREDACTED] -fh [HANDLERREDACTED] --function-role [ROLEREDACTED] --function-memory-size 1024 --function-timeout 60 --disable-interactive true --no-build

**Screenshots**

**Your Environment**
 - VSTS or Azure Devops (on-prem or cloud based?): Azure Devops (cloud)

Building on "Hosted Ubuntu 1604" agent.

**Comment by johniwasz** [comment]
WRT, "you will need to logout or restart your session before running the tool you installed."

Indeed, that same phrase caught my attention as well and I suspected it could be an issue.  I reviewed prior build logs that were running successfully with version 1.1.8 and found that same text in the output of the task that installed the AWS lambda tools, which suggested that it can ruled out as root cause.

I can send you detailed build logs from my Azure Devops process of the build process running successfully with version 1.1.8 and then failing with 1.3.0 in a direct message or email. I just don't want to post them on a public thread.

Before submitting here, I also opened a trouble ticket though my AWS account. If you have access to customer-submitted trouble tickets, you'll find the logs mentioned associated with Case ID 6172251411.

**Comment by hunterwerlla** [comment]
The root issue is that the .net lambda tools are now global: https://aws.amazon.com/blogs/developer/net-core-global-tools-for-aws/ . Since this task has not been updated since then, it is not auto installing the tools properly. 

To work around this, you need to use Amazon.Lambda.Tools version 2.2.0 or earlier in your lambda's csproj. We will work on refreshing this task to work properly with the global tools.

**Comment by johniwasz** [comment]
I see. That makes sense. Thanks to you and your team for tracking that down.

I'll adjust accordingly, although there may be some features that I'm using in the 3.* version of the tool that's missing in 2.2.0. Off the top of my head, I don't recall what, but I have a sense that something else will break when I roll back to version 2.2.0. 

I realize this isn't part of this request, but I would love to be able to create function layers with the toolkit extensions. It would simplify the build process. If that's not already a feature request, I'll add that.

**Comment by johniwasz** [comment]
I can confirm that the build is now succeeding with projects that include the following reference with one exception:

  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.2.0" />
  </ItemGroup>

I am using .NET Core 2.2 per the documentation provided here:

https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/

This task that packages this lambda results in the following:

```
Performing package-only build of function, output package will be placed in /home/vsts/work/1/a/[REDACTED].zip
Path to tool: /usr/bin/dotnet
[command]/usr/bin/dotnet lambda package -o /home/vsts/work/1/a/[REDACTED].zip --region us-east-1 -fn [REDACTED] -fh [REDACTED] --function-role [REDACTED] --function-memory-size 1024 --function-timeout 30 --disable-interactive true --no-restore
Amazon Lambda Tools for .NET Core applications (2.2.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
Executing publish command
... invoking 'dotnet publish', working folder '/home/vsts/work/1/s/src/[REDACTED]/bin/Release/netcoreapp2.2/publish'
... publish: Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish: MSBUILD : error MSB1009: Project file does not exist.
... publish: Switch: false
Failed to create application package
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 255
##[section]Finishing: [REDACTED] Task
```

It was working with version 1.1.8 of the extension. 

I'll find a work around, but I expect anyone else trying to build with custom runtimes will encounter the same issue.

**Comment by hunterwerlla** [comment]
@johniwasz A workaround that works on hosted agents is to make a cmd/bash script before like this:
```
dotnet tool install --global Amazon.Lambda.Tools --version 3.1.1
dotnet tool update -g Amazon.Lambda.Tools
```
I'm working on the fix that will make it part of the task

**Comment by hunterwerlla** [comment]
This is now fixed in the 1.5 release

**Comment by ADGrant** [comment]
I have 1.5 installed and I am still seeing **No executable found matching command "dotnet-lambda"**

**Comment by BrycePC** [comment]
Are there any further updates to this? I am also using the latest Amazon.Lambda.Tools in Azure Devops for deploying a serverless application to AWS, and am still getting the error:

No executable found matching command "dotnet-lambda"

**Comment by DimonLuk** [comment]
The same thing, any suggestions?

**Comment by johniwasz** [comment]
I've had the same issue. In summary, I used built out the dotnet-lambda command directly rather using the lambda or stack deployment task in the tools.

First, I removed the Amazon.Lambda.Tools reference from my project(s):
<DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.2.0" />

The dotnet-lambda not found issue can be resolved by referencing the dotnet-lambda executable directly. After installing the lambda tools using a custom .net core command that runs:

dotnet tool install Amazon.Lambda.Tools -g 

I then install Python followed by running the command line operation:

pip install awscli

Then, I add an AWS Shell Script Task and run:

$HOME/.dotnet/tools/dotnet-lambda package-ci -ot $1-outfile.template --region $1 --s3-bucket $2 --s3-prefix cloud-formation/[YourProjectFolderHere]/ --disable-interactive true --no-restore 

The Working Directory option in the task is set to the project folder I want to build.

I pass in the following in the Arguments:

$(region) $(utilitybucket)

The region and utility bucket are pipeline variables.

The $HOME/.dotnet/tools/ prefix is the default global tools installation directory on Linux. On Windows, it's:

%USERPROFILE%\.dotnet\tools\

**Comment by DimonLuk** [comment]
Find a simple solution that works for me (on Linux):
```bash
dotnet tool install --tool-path=/path/to/dotnet Amazon.Lambda.Tools
```
Then set PATH variable to  be `$PATH:/path/to/dotnet` in any way comfortable for you

**Comment by brunodavi** [comment]
export PATH="$PATH:$HOME/.dotnet/tools" > ~/.bashrc

close your terminal and test `dotnet lambda` or `dotnet-lambda`

**Comment by brunodavi** [comment]
> @johniwasz A workaround that works on hosted agents is to make a cmd/bash script before like this:
> 
> ```
> dotnet tool install --global Amazon.Lambda.Tools --version 3.1.1
> dotnet tool update -g Amazon.Lambda.Tools
> ```
> 
> I'm working on the fix that will make it part of the task

Tank's, when reinstall show how binary path
