### ISSUE TITLE
Beanstalk deploy fails when version label already exists

### ISSUE THREAD

**Issue by lukewis** [aws/aws-vsts-tools#57]
We have a CI process setup where we deploy to beanstalk from a release definition using the Deploy to Beanstalk task.  We specify the version label to be the same as our build number, which is in the format 20180122.6.  We have several environments (dev, qa, staging, prod) and we would like to deploy the same binary to all environments.  The problem is that the task seems to assume that it should ALWAYS upload a binary, and fails if it already exists.  This results in our "first release" (say to dev) works, but then all subsequent releases (qa, staging, prod) fail because the version label already exists.  Could the task be updated to skip uploading the binary if it already exists, or is there a different recommendation to handle this use case?

**Comment by steveataws** [comment]
Hi,

The CodeDeploy task was updated last week to allow it to take a previously uploaded bundle (in S3) for the deployment and we were planning on extending the same support out to the Beanstalk task, now that we have confirmation from the requester that the change works for them. 

Would extending the Beanstalk task this way solve your problem, so you could upload once (say using the S3 Upload task) and then have your Beanstalk task configurations simply reference the uploaded object? or of course rely on your first environment deployment to do the upload and configure the rest to simply reuse the artifact.

**Comment by lukewis** [comment]
Thanks for the response, @steveataws.  I think that will address our problem.  In order for that to work, the S3 upload task would either need to A) Do nothing if the file already exists in S3, or B) Overwrite the existing file (if it already exists in S3).  Either would be fine in our case, but we wouldn't want that task to FAIL if the file exists.  Do you happen to know how that task behaves?

**Comment by steveataws** [comment]
The S3 Upload task will just overwrite the existing object in S3. I was thinking along the lines of a build def that ends with pushing the new artifact zip to S3, and then one or more release definitions (one per EB environment) that contain the Beanstalk deployment task configured to use a pre-existing object within S3. Of course you'd need to pass the object key to the release definitions but you mentioned you know the format of that based on build number.

Or you could have a single build def that publishes to S3, then multiple copies of the Beanstalk task (again, one per env) that are configured to use the existing artifact. None of the Beanstalk tasks would do any uploading.

Thoughts?

**Comment by lukewis** [comment]
This sounds like it will work.  One additional question though....From my understanding, the current task does 3 steps:

1. Upload to S3
2. Register version with Beanstalk Application
3. Deploy version to Beanstalk Environment

It sounds like your proposed solution will allow skipping step 1, but I'm concerned that it's actually step 2 that's failing for us.  Does your solution address step 2 in this process, or am I misunderstanding something?

**Comment by steveataws** [comment]
It didn't, but it can. So basically we'd extend the task with an option to 'Deploy existing version' with a corresponding field to specify the version id.

**Comment by lukewis** [comment]
I think my issue is that at the time a release definition runs, I don't know whether or not the version has already been registered with Beanstalk.  I was hoping that the task could handle the complexity of querying Beanstalk and only registering the version if it doesn't already exist.  Is that what you mean by your suggestion?

**Comment by steveataws** [comment]
Ah, I see what you mean. Sure, I'll extend the task so that it has an option to check for an existing version and skip (a) the upload and (b) any 'already exists' error when it exists. Something like a checkbox on the task that reads 'Check for existing version and continue if already registered.' (unchecked by default, which will yield the current behavior).

Sound OK?

**Comment by lukewis** [comment]
Yep.  I think that sounds good.  So to summarize, there will be two new options.  Option 1 determines the upload (S3) behavior, and option 2 determines the Beanstalk behavior.

- Option 1:  Either specify a zip file to upload, or choose an existing S3 resource (based on url?) - If you choose a zip file to upload, and that artifact already exists in S3, it will be overwritten.  If you choose an existing S3 url, no upload will be performed.
Option 2: Continue if version exists - This doesn't impact the first option (whether or not to upload), it will only impact whether an existing version will be deployed or reported as an error

Is that correct?

**Comment by steveataws** [comment]
Yes, that's the thinking - the only change is that the S3 artifact is identified by bucket and keyname rather than url (to be consistent with our other tasks).

**Comment by steveataws** [comment]
I've just released v1.0.18 which contains a new task enabling you to create an application revision for Beanstalk separate from the deployment process. This should enable your build to upload the new content and create a revision (as a single operation, although you can also upload the bundle separately and create the new revision by referencing the bucket and object key for the upload). The existing deployment task has been extended with a new option enabling you to specify the version number of the application to deploy.

These changes should enable your scenario of a build that produces the artifacts and registers a new version from them, and subsequent tasks to perform deployment of the revision (without any uploads) to your environments.

Let us know what you think, and if it all works ok for your scenario if we can resolve the request.

**Comment by steveataws** [comment]
Resolving as this has now been released and available for a few days.

**Comment by lukewis** [comment]
@steveataws , sorry it took me a few days to test, but the new task you introduced does not solve our problem.  We build 10-15 times per day, but we only release 1-2 times.  Because of that, we only push to S3 for a release (not every build).  Therefore, at the time the release definition runs, it has no way of knowing whether or not the application version already exists.  I like your [original proposal ](https://github.com/aws/aws-vsts-tools/issues/57#issuecomment-360335469) better.  It seems that register application version still needs the ability to be "tolerant" of an existing version.

**Comment by jnyrup** [comment]
Just wanted to chime in, that we're having similar issues when a version label already exists.

My current workaround is a two-task solution
1. Use "AWS Elastic Beanstalk Create Version" to create a new version.
    * Enable "Continue on error" to handle if the version already exists.
2. Use "AWS Elastic Beanstalk Deploy Application" to deploy an existing version.

The only real downside with this workaround is that if the version already exists, the first task (and hence the entire stage) will be marked as *partially* successful.

**Comment by jeffminsungkim** [comment]
@jnyrup I don't see any deploy option for case 1. How should I handle if the version already exists?

**Comment by jnyrup** [comment]
@jeffminsungkim I'm using a Task Group consisting of these two Tasks.
![image](https://user-images.githubusercontent.com/919634/88791792-8ed95d00-d19a-11ea-83c4-d6e689f4ef1f.png)

# Create Version
## Try to create a new version
![image](https://user-images.githubusercontent.com/919634/88792012-e8418c00-d19a-11ea-92d4-1a1e6d5f25e1.png)
--
![image](https://user-images.githubusercontent.com/919634/88791917-cb0cbd80-d19a-11ea-940d-2a00e6478794.png)
--
## if already exists, do not fail but continue
![image](https://user-images.githubusercontent.com/919634/88791811-9993f200-d19a-11ea-91e8-4b5c8b00a2c6.png)

# Deploy Application
![image](https://user-images.githubusercontent.com/919634/88791951-d3fd8f00-d19a-11ea-9df8-4b23fe5389d1.png)
--

## Deploy the same version as specified in the first task.
![image](https://user-images.githubusercontent.com/919634/88791967-da8c0680-d19a-11ea-9964-25e22af369c6.png)
